name: Offline Server Check
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run offline server check
        env:
          ALLOW_CAMERA: "0"
          PORT: "5000"
        run: |
          python tools/dev/offline_server_check.py
